### ISSUE TITLE
Create releasing instructions

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#10]
In order to support repeatable builds and get human coverage on the release process, we should create release instructions. These instructions should be able to be followed by any project maintainer and they should live in the repo as markdown.

Other repos (like[ java instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/RELEASING.md)) should be used as a guide. To the extent that it makes sense for Android, we should try and follow a very similar process.

**Comment by LikeTheSalad** [comment]
I think this is done now
