### ISSUE TITLE
Automate dependency checks (renovatebot)

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#13]
We need to enable the bot that checks for and PRs dependency updates. In the other java repos they use dependabot and newly renovatebot in instrumentation. We should decide which one we want to use and get it wired up.

**Comment by trask** [comment]
`-examples`, `-contrib` and `-instrumentation` are all using renovate now, see https://github.com/open-telemetry/opentelemetry-java-contrib/pull/978 for reasoning:

>
> Pros for Renovate:
> * Supports grouping dependency updates into a single PR. There are some [preset groupings](https://docs.renovatebot.com/presets-group/), and you can configure others. This should allow us to reduce the volume of dependency update PRs.
> * Auto-updates gradle wrapper versions also (no need for third party github action, which also doesn't trigger CI when it's PRs are opened, at least without giving opentelemetrybot write permission to the repo which we are trying to avoid)
> * Renovate picked up one additional dependency update which dependabot missed: https://github.com/open-telemetry/opentelemetry-java-contrib/pull/967
> * Renovate allows us to configure a fixed version that we don't want to update, e.g. micrometer 1.1.0, while auto-updating other versions, which is nice for keeping the tests up-to-date and running against the latest version
