### ISSUE TITLE
Add HttpUrlConnection instrumentation tests

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#148]
The footprint of #133 is pretty sizable and will be experimental for a time, so we have decided to defer the tests to a future PR. This is a tracking issue to create appropriate an appropriate `InstrumentationTest` similar to the okhttp test. This should run on device and exercise the instrumentation against the testing endpoint.

**Comment by surbhiia** [comment]
Do assign this to me! Thanks :)

**Comment by breedx-splk** [comment]
We have this now!
