### ISSUE TITLE
Okhttp 4.12 forces kotlin upgrade to 1.9 which might be problematic for some customers

### ISSUE THREAD

**Issue by surbhiia** [open-telemetry/opentelemetry-android#169]
An issue was raised on same [here](https://github.com/open-telemetry/opentelemetry-java/issues/6026). 

Should this repo try to have two versions of okhttp auto-instrumentation -> okhttp3+ and okhttp4.12+ to cover all customers?

**Comment by marandaneto** [comment]
One option is to force the okhttp auto-instrumentation to set `apiVersion` and `languageVersion` to at least `1.6` which is the oldest version not deprecated yet.
https://kotlinlang.org/docs/gradle-compiler-options.html#attributes-common-to-jvm-and-js
Maybe that works? not sure if it works when it pulls a compiled jar already or if the compiler is yet able to desugar everything newer.

**Comment by theAkito** [comment]
Indeed. This is a problem. Is there an issue like this on OkHttp's side somewhere?

**Comment by LikeTheSalad** [comment]
> Indeed. This is a problem. Is there an issue like this on OkHttp's side somewhere?

Yes, we discussed this in this [OkHttp issue](https://github.com/square/okhttp/issues/8139).
