### ISSUE TITLE
Define endpoint for collector

### ISSUE THREAD

**Issue by neugartf** [open-telemetry/opentelemetry-android#257]
Pardon me to open an issue for this but I'm completely lost on how to even define the endpoint for the external collector 🤔.
I would have expected it in the `OtelRumConfig`, but it is not there.
On a normal java client i'd guess you can get away with `OTEL_EXPORTER_OTLP_ENDPOINT`, but this doesn't seem to be the best way for Android.

Any lead to configure this?

Thanks! :)

**Comment by LikeTheSalad** [comment]
Hi @neugartf 

At the moment there's no config for it, though I agree a good place should be `OtelRumConfig`, so it most likely will be added there soon. This project is still a work in progress, so even though it can already help send Android telemetry, the initialization APIs are not fully developed.

In the meantime, the initialization requires manual work to set up all signals properly. You can take a look at [this gist](https://gist.github.com/LikeTheSalad/162278712aa04add0f19f4c2c008e7b6) that shows how you could do so for now. However, bear in mind that we're constantly adding changes to this repo, so it should change (for the better) soon.

**Comment by neugartf** [comment]
Thanks for the quick response and the `gist`. That will certainly help!
>.>
