### ISSUE TITLE
Generate configuration event at startup

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#277]
Relates to #168.

As part of #276, the configuration was decoupled from the initialization events. This TODO says that we should figure out how to pass the config as a map: https://github.com/open-telemetry/opentelemetry-android/pull/276/files#diff-6f33477d17cf7e6844b9afbc97741d317291d28b233fb28f810359611325274fR376

It's really helpful to have an event at startup that provides the o11y practitioner with details about the RUM/agent configuration.

**Comment by LikeTheSalad** [comment]
Apart from avoiding a circular dependency, do you think there are other reasons where transforming the config object into a map could be beneficial? I'm asking because I think we could work around the circular dependency issue, so we might be able to avoid doing this work altogether.

**Comment by LikeTheSalad** [comment]
I think this issue is no longer needed.

**Comment by breedx-splk** [comment]
Yeah, certainly as written now the "configuration" isn't a singular thing that we can absorb and digest....and instead it is spread around with each individual instrumentation. 

The original goal of this was to provide additional details about how the agent (and otel) are configured. Imagine looking at a session in a RUM tool and being able to ask easily:

* Was disk buffering enabled/disabled?
* Was there a custom sampler being used?
* What instrumentations were installed?
* What interval are slow renders being polled at?
* etc. etc.

This stuff is metadata, but super useful if/when you start questioning how the agent is behaving. Very very useful in troubleshooting.

I guess I'll close for now until there's a more specific ask.
