### ISSUE TITLE
Question: How to enable debug logging?

### ISSUE THREAD

**Issue by MRezaNasirloo** [open-telemetry/opentelemetry-android#302]
How do I enable logging in debug environments? 
What I would like to see in the logcat are:

1. A Metric is being recorded and its attributes
2. Network calls that the sdk makes
3. Any errors or warnings that occurs

I tried these properties in gradle.properties with no success

```
otel.javaagent.debug=true
io.opentelemetry.level=VERBOSE
```

**Comment by aldoKelvianto** [comment]
AFAIK, the current OTel Android SDK doesn't have support for a LogCat Exporter yet (the Java SDK has Exporters to console, but LogCat or Timber is Android-specific).

However, we can write our own [Exporter](https://opentelemetry.io/docs/collector/) like this:

```kotlin
class LogCatSpanExporter: SpanExporter {
   override fun export(spans: MutableCollection<SpanData>): CompletableResultCode {
       spans.forEach {
           Log.d("logcat-tag", "SpanData: $it")
       }
       return CompletableResultCode.ofSuccess()
   }

   override fun flush(): CompletableResultCode {
       return CompletableResultCode.ofSuccess()
   }

   override fun shutdown(): CompletableResultCode {
       return CompletableResultCode.ofSuccess()
   }
}
```

And then add it to the OTel RUM:

```kotlin
val otelRumBuilder: OpenTelemetryRumBuilder = OpenTelemetryRum.builder(this, config)
   .addSpanExporterCustomizer {
       OtlpHttpSpanExporter.builder()
           .setEndpoint("http://10.0.2.2:4318/v1/traces")
           .build()
   }
   .addSpanExporterCustomizer {
       LogCatSpanExporter()
   }

val rum: OpenTelemetryRum = otelRumBuilder.build()
```

<img width="314" alt="example-output-1" src="https://github.com/open-telemetry/opentelemetry-android/assets/5099600/fd27fb05-84f1-43cb-83fd-5b3c9120d4c1">

![example-output-2](https://github.com/open-telemetry/opentelemetry-android/assets/5099600/674ebd13-a986-4a43-84e6-7e1771aab7aa)


Additionally, some events are logged by the SDK, such as frozen frames, slow renders, and network events:

```java
Log.d(RumConstants.OTEL_RUM_LOG_TAG, "* FROZEN RENDER DETECTED: " + duration + " ms. " + count + " times");
Log.d(RumConstants.OTEL_RUM_LOG_TAG, "* Slow render detected: " + duration + " ms. " + count + " times");
Log.d(RumConstants.OTEL_RUM_LOG_TAG, " onAvailable: currentNetwork=" + activeNetwork);
```

I think it's also possible to use [a Processor](https://opentelemetry.io/docs/collector/configuration/#processors), like this:

```java
// OtelRumConfig.java
public boolean isLogCatEnabled() {
   return logCatEnabled;
}

// OpenTelemetryRumBuilder.java
if (config.isLogCatEnabled()) {
   // Add processor that prints to LogCat using Log.d or Timber
}
```

However, this would mean we need to modify the SDK (I'm not too sure about this approach).

**Comment by breedx-splk** [comment]
Hey @MRezaNasirloo thanks for the question. I think this is probably a duplicate of #142 , which is intended to create the thing that you are asking about. We are looking for contributors who are able to help building this feature.

In the meantime, what @aldoKelvianto suggested is very close to what you can use (thanks for helping out here, @aldoKelvianto !). One thing to point out, is that it looks like the above kinda misuses `addSpanExporterCustomizer()` -- if you check out the javadocs:

```
    /**
     * Adds a {@link Function} to invoke with the default {@link SpanExporter} to allow
     * customization. The return value of the {@link Function} will replace the passed-in argument.
     *
     * <p>Multiple calls will execute the customizers in order.
     */
```

So you have to be careful calling it twice, like the above. Ideally, the `LogCatSpanExporter` above should take the existing exporter and wrap/delegate to it. 

@MRezaNasirloo if you agree that #142 covers this, then let's close this one. Thanks!
