### ISSUE TITLE
Unable to ingest logs, traces from ANDROID, IOS App to Azure.

### ISSUE THREAD

**Issue by manashbob** [open-telemetry/opentelemetry-android#326]
We followed this to setup Opentelemetry in ANDROID and IOS app, but unable to ingest logs, traces to Azure Application Insights or to Azure Log Analytics Workspace. Is there any proper document or another code repo which we can refer to ingest logs, traces from Android and IOS apps to Azure?

**Comment by LikeTheSalad** [comment]
Hi @manashbob 

Please can you provide more details on what guide you followed to set up Opentelemetry within your Android app?

At the moment OTel Android doesn't configure any exporter for logs. It's something that it should do in the future when it becomes stable, but for now, there would be some work needed to make it work. [This gist](https://gist.github.com/LikeTheSalad/162278712aa04add0f19f4c2c008e7b6) should help give more info on how to do so in with the current state of OTel Android.

**Comment by manashbob** [comment]
Thank you @LikeTheSalad. My Dev Team followed https://github.com/open-telemetry/opentelemetry-android
There is no way even to enable trace from Android using OTEL SDK?

**Comment by LikeTheSalad** [comment]
> There is no way even to enable trace from Android using OTEL SDK?

Using both, the OTel Java SDK directly and also the Android SDK, it's possible to do tracing, logging, and sending metrics. Although at the moment it requires a fair amount of manual configuration to make it work. That's one of the reasons why the OTel Android project exists, to make the setup more straightforward for Android apps. However, OTel Android hasn't reached that level of maturity yet, so in the meantime, the options that you might want to take a look at are the following:

- Using the OTel Java SDK directly by following its [manual instrumentation](https://opentelemetry.io/docs/languages/java/instrumentation/) guide.
- Using OTel Android while manually setting the signal processors/exporters as it was done in [this gist](https://gist.github.com/LikeTheSalad/162278712aa04add0f19f4c2c008e7b6). This option is quite similar to the first one right now, in the sense that you'd need to set up a lot of configs manually, however, there's the benefit that you'd get the features listed [here](https://github.com/open-telemetry/opentelemetry-android#features) out of the box.

**Comment by trask** [comment]
Hi @manashbob, are you using the [Azure Monitor OpenTelemetry Exporter](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter#azure-monitor-opentelemetry-exporter-client-library-for-java), or another way to send the telemetry to Azure Monitor? Thanks

**Comment by manashbob** [comment]
Hi @trask, we tried this but no luck. Not sure what my Dev Team done integrating Opentelemetry SDK, they are even not able load libraries .

// OpenTelemetry API
implementation 'io.opentelemetry:opentelemetry-api:1.35.0'
// OpenTelemetry SDK
implementation 'io.opentelemetry:opentelemetry-sdk:1.35.0'
// Exporter for sending data to Azure Monitor
implementation 'com.azure:azure-monitor-opentelemetry-exporter:1.0.0-beta.21'

If you have any specific document link which can help us setting of OTEL SDK and integrate Azure monitor, please share. 

Thanks a lot!

**Comment by mattmccleary** [comment]
Hi @manashbob - there's no official documentation or support for this from the Azure side, but we'd be happy to meet anyway and understand what you're doing and see if we have any ideas for how to unblock you. Feel free to send an email to OTel@microsoft.com.

**Comment by manashbob** [comment]
Hi @mattmccleary , Thank you. 

We are planning to retrieve traces, logs from Android and IOS app and forward it to Azure Application Insight or Azure Log Analytics Workspace, we referred 
https://github.com/open-telemetry/opentelemetry-android and 
https://www.alibabacloud.com/help/en/sls/user-guide/import-trace-data-from-android-apps-to-log-service-1?spm=a2c63.p38356.0.0.6c14634fbINu5f, 
but no luck. 
Even they didn’t see any error in app, but nothing captured in Application insight.

**Comment by trask** [comment]
hi @manashbob, I'd recommend opening this issue in https://github.com/Azure/azure-sdk-for-java (for the [azure-monitor-opentelemetry-exporter](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter) component)

unfortunately it looks like currently the [azure-monitor-opentelemetry-exporter](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter) uses Java APIs that are not supported by Android, and so some work will need to be done in order to support Android
