### ISSUE TITLE
Configuring session handler timeout time

### ISSUE THREAD

**Issue by Archish27** [open-telemetry/opentelemetry-android#329]
Currently, as per the [code ](https://github.com/open-telemetry/opentelemetry-android/blob/66de8ae9a2d993e107765248a75a8183b9e35204/android-agent/src/main/java/io/opentelemetry/android/SessionIdTimeoutHandler.java#L12) We have default timeout of 15mins.

Need a way for configuring this timeout during initialization.

**Comment by LikeTheSalad** [comment]
It seems like a config param [here](https://github.com/open-telemetry/opentelemetry-android/blob/66de8ae9a2d993e107765248a75a8183b9e35204/android-agent/src/main/java/io/opentelemetry/android/config/OtelRumConfig.java#L20) should be ideal for this use case.
