### ISSUE TITLE
Enable AndroidLifecycleInstrumentation by default

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#337]
The `AndroidLifecycleInstrumentation` is not enabled by default, and I think that's a mistake. This instrumentation helps to report startup time and also makes available the name of the "current screen" so that it can be added as an attribute on other data (spans/events). 

This can/should probably wait until the changes that @LikeTheSalad is proposing around the instrumentation API have settled a little big, but I feel like most users definitely want this instrumentation turned on by default.

**Comment by LikeTheSalad** [comment]
I think this should be the case now.

**Comment by breedx-splk** [comment]
Yeah, using the demo app I was able to confirm that both the `ActivityLifecycleInstrumentation` and the `FragmentLifecycleInstrumentation` are being installed...and although we don't have any Fragments currently, the activity instrumentation seems to be working and putting the appropriate events on the activity lifecycle spans:

<img width="879" alt="image" src="https://github.com/user-attachments/assets/486559fd-ef54-46d6-a0db-9d1357833e51">
