### ISSUE TITLE
Configurable options

### ISSUE THREAD

**Issue by LikeTheSalad** [open-telemetry/opentelemetry-android#39]
* Enabling/disabling each automatic signal generator (Crash reporting, ANRs, Activity/Fragment monitoring, Frozen render detection).
* Enabling/disabling offline buffering, as well as providing config options for the max cache size and how often the stored signals should get exported.
* Provide exporter customizers for all signals.
* Provide a custom exporter for each signal (probably already sorted by exporter customizers).

#### Options for making common configs more straightforward

The following config options would be very convenient to use since they can reduce a lot of boilerplate and repetition (when the same config is needed for all signals). Most of them should be possible to achieve by using the `add[Tracer|Meter|Logger]ProviderCustomizer` builder's methods, but in a more verbose way.

* Adding dynamic global attrs to all signals, there's [an issue](https://github.com/open-telemetry/opentelemetry-android/issues/128) for it.
* Provide a Resource for all signals.
* Provide a Clock for all signals.
* Provide filtering mechanism for signals, to prevent exporting them based on some predicate (this one is not possible to set using the `add[Tracer|Meter|Logger]ProviderCustomizer` builder's methods but should be possible by using exporter customizers).

**Comment by breedx-splk** [comment]
Oh this is much too broad to be actionable. :) Placeholder is totally fine for now, but pease either provide a list of "opinions" or narrow this down to one specific on for starters. Thanks.

**Comment by LikeTheSalad** [comment]
Hi @breedx-splk - I've added the overall config options that I think we could provide, not only the "opinions" ones. Probably some configs are already possible, though I wanted to have an overall high-level idea here and then discuss about which ones exist or which ones shouldn't be added, etc. Please let me know what you think, once we find out which ones should be implemented and how, we could create issues for each and close this one!

**Comment by breedx-splk** [comment]
Yeah this is great, I love it. I think all the items you've outlined above are great. The only real challenge I see presently is that "all signals" encompasses events, which are still being fleshed out. Shouldn't prevent us moving forward, though.

**Comment by LikeTheSalad** [comment]
Yeah, that's true, although since events run with the same processors and exporters as logs, I'd argue that the signal itself is the log and the event would be a log format, so most likely any configs added to the logs exporters/processors shouldn't get affected by future changes added to the events' spec. Though I agree we shouldn't add any event-specific config options until that spec is polished.

**Comment by LikeTheSalad** [comment]
I think all the things proposed here are either addressed already or have their own issue.
