### ISSUE TITLE
De-static HttpUrlInstrumentationConfig

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#418]
As part of #133, I put in [this comment](https://github.com/open-telemetry/opentelemetry-android/pull/133/files#r1630319888) do describe how I think the config ought to work.

This is a tracking issue so that we can circle-back after #133 is merged.

**Comment by surbhiia** [comment]
#592 resolves this

**Comment by breedx-splk** [comment]
Ok, fixed in #592.
