### ISSUE TITLE
Replace errorprone with another static analysis tool

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#43]
In version 3.0.0, errorprone [removed support for Android](https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v3.0.0). ☹️ As a result, the plugin we used to use now does nothing, and errors are just ignored. This is a problem, because simple mistakes could slip through without static analysis.

So we should find and implement reasonable replacement for errorprone.

**Comment by LikeTheSalad** [comment]
This is unfortunate. Although I think I understand why they did it, Android's compilation plugin has changed a lot recently so it's difficult to keep up with all the API breaking changes.

If it helps, I see that they still mention [here](https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v3.0.0) that their tool could still work on android projects, is just that we'd have to manually plug it into the android compilation process on our side. So, I could take a look at that option in case there's no other alternative.

**Comment by LikeTheSalad** [comment]
It seems like this enables it back, I haven't checked if test sources are still disabled from running these checks, which I think is the expected behaviour: https://github.com/open-telemetry/opentelemetry-android/pull/46

**Comment by breedx-splk** [comment]
This is looking good, nice job finding a way to get it working again! 🤘🏻 
I opened #48 to help with the existing violations. If we merge that first, I think #46 will be good.
