### ISSUE TITLE
Run androidTests as part of CI

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#501]
Right now, we have some androidTests that do not yet automatically run. We should build automation that runs these as part of our  CI builds. 

Open question: At what step(s) should we run them? PR? Main merge? Nightly? 

Open question: What devices with what android versions?

Are there pros/cons to not just having it be part of every PR build?

**Comment by breedx-splk** [comment]
One options for this: https://github.com/marketplace/actions/android-emulator-runner

**Comment by LikeTheSalad** [comment]
Done in #509
