### ISSUE TITLE
AndroidInstrumentationRegistry should have a clearer purpose/api

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#502]
This is a [follow-up from this comment](https://github.com/open-telemetry/opentelemetry-android/pull/498/files#r1697661012).

The `AndroidInstrumentationRegistryImpl` seems like it's intended to ONLY encapsulate the auto-discovered instrumentations available on the classpath. Even though `internal`, having a `register()` method is slightly confusing (it's unclear when that should/could be used). Furthermore, it appears that any interactions with the registry (`get()` or `getAll()`) will cause the lazy field to be initialized, which _will_ load instrumentation classes. Depending on the configuration, this may not be what users expect, and at worst could have side effects if instrumentations are behaving poorly during construction.

Propose removing `register()` from the registry and renaming the registry to something like `AutodetectedClasspathInstrumentations`, and only calling `get()` or `getAll()` when the configuration has `discoverInstrumenations = TRUE`.

**Comment by LikeTheSalad** [comment]
Done in #516
