### ISSUE TITLE
Can't configure ContextPropagators in OpenTelemetry instance

### ISSUE THREAD

**Issue by GerardPaligot** [open-telemetry/opentelemetry-android#56]
**Context**
Because `OpenTelemetry` instance is created internally inside `OpenTelemetryRumBuilder` class, we can't add custom configuration in `OpenTelemetry` object but it could be useful for some cases.

e.g.: If I want to configure `ContextPropagators` to connect my traces with other external services, I can't with the actual codebase.

**Suggestions**
1. Expose OpenTelemetry builder to let the developer configure what he/she want before the Rum configuration.
2. or add a new function in `OpenTelemetryRumBuilder` to configure a `ContextPropagators`.

**Comment by breedx-splk** [comment]
Hi @GerardPaligot. While yes, the traditional use case was to have OpenTelemetry RUM create the otel sdk for you (created internally, as you pointed out), we did add method to `OpenTelemetryRum` that you can pass your own SDK instance to. Check out [OpenTelemetryRum.builder(app, sdk)](https://github.com/open-telemetry/opentelemetry-android/blob/main/instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java#L49) and see if that can work for you.

Be warned, that's a fairly big hammer and you'll have to make sure that you get the rest of the sdk wired up for your needs...but it sounds that's the option 1 you proposed.

The design of this is still flexible, so please let us know how it goes for you so we can make informed decisions about the approach. Thanks!

**Comment by GerardPaligot** [comment]
Yes, I used this function to add lifecycle instrumentation in my RUM OTeL object:

```kotlin
internal fun OpenTelemetryRumBuilder.addLifecycleInstrumentation(
    screenTracker: VisibleScreenTracker,
    startupTimer: AppStartupTimer = AppStartupTimer()
): OpenTelemetryRumBuilder {
    return this.addInstrumentation { app ->
        AndroidLifecycleInstrumentation.builder()
            .setVisibleScreenTracker(screenTracker)
            .setStartupTimer(startupTimer)
            .setTracerCustomizer { tracer ->
                return@setTracerCustomizer Tracer { spanName ->
                    val component = if (spanName == RumAttributeKeys.APP_START_SPAN_NAME) {
                        AttributeKeys.Features.COMPONENT_APPSTART
                    } else {
                        AttributeKeys.Features.COMPONENT_UI
                    }
                    tracer.spanBuilder(spanName)
                        .setAttribute(AttributeKeys.COMPONENT_KEY, component)
                }
            }
            .setScreenNameExtractor(ScreenNameExtractor.DEFAULT)
            .build()
            .installOn(app)
    }
}
```

But I created a sample app to test this with the minimum of code and it works well. I probably do something wrong somewhere else in my code. I close this and will reopen it if I can reproduce it.

**Comment by GerardPaligot** [comment]
Sorry, I posted and close the wrong issue. :)

**Comment by GerardPaligot** [comment]
> we did add method to OpenTelemetryRum that you can pass your own SDK instance to. Check out [OpenTelemetryRum.builder(app, sdk)](https://github.com/open-telemetry/opentelemetry-android/blob/main/instrumentation/src/main/java/io/opentelemetry/android/OpenTelemetryRum.java#L49) and see if that can work for you.

Thanks for showing me this, I didn't see it but when I check the implementation, you need to write so much more code than using this function `OpenTelemetryRumBuilder builder(Application application)` and the risks of misconfiguration are much higher.

Maybe a better implementation could be to pass an `OpenTelemetrySdkBuilder` object to be able to continue to instrument it in the RUM part. These calls should be probably always applied:

```java
        OpenTelemetrySdk sdk =
                OpenTelemetrySdk.builder()
                        .setTracerProvider(buildTracerProvider(sessionId, application))
                        .setMeterProvider(buildMeterProvider(application))
                        .setLoggerProvider(buildLoggerProvider(application))
                        .build();
```

I wonder if it's even a good idea to expose this function:

```java
    static SdkPreconfiguredRumBuilder builder(
            Application application, OpenTelemetrySdk openTelemetrySdk) {
        return new SdkPreconfiguredRumBuilder(application, openTelemetrySdk);
    }
```

What do you think?

**Comment by breedx-splk** [comment]
Yeah, it is unfortunate that it does require quite a bit more heavy lifting when using the "bring your own" (BYO) SDK. Being able to BYO SDK and do all the configuration outside, however, was ultimately one of the first things that users started asking for when the code was donated.

I think that your idea of passing the builder is rather interesting, but I have a couple of concerns. 

First, it's hard for the builder to then know at build time which pieces of the sdk building have been preconfigured externally, and which pieces should be set/overridden by the RUM builder. In other words, has the user already set up their own tracer provider? How can we tell? And if they have, should we override it or somehow try and wrap it with our own? Seems confusing.

Secondly, if the RUM builder ultimately calls `.build()` on the `OpenTelemetrySdkBuilder` passed to it, then the user could ALSO call `.build()` and you'd have two potentially incompatible instances of the SDK floating around. This also seems like a path to mayhem, and is generally why I suspect having builders as dependencies is an antipattern (or at least a code smell).

I'll take a look and see what an additional API to configure propagators might look like....

**Comment by breedx-splk** [comment]
@GerardPaligot Please take a look at #71 and see if something like that would fit your needs. Thanks!

**Comment by GerardPaligot** [comment]
Your contribution fit exactly my needs! 🙏 
Thanks!

**Comment by breedx-splk** [comment]
Hey @GerardPaligot looks like #71 fixed this for you. Please reopen or start another issue if this is still a concern. Thanks!
