### ISSUE TITLE
`onActivityPreCreated` never called for fragment post 29

### ISSUE THREAD

**Issue by GerardPaligot** [open-telemetry/opentelemetry-android#57]
**Context**
In `RumFragmentActivityRegisterer` class, you have two implementations to track fragment lifecycle before and after Android API version 29 but when I'm testing the implementation post version 29 (with a device running Android version 12, so API 32), `onActivityPreCreated` is never called in the lifecycle callback attached to my fragments in my codebase.

**Suggestion**
Use `onActivityCreated` for all versions which is call by Android version before and after the version 29.

**Comment by breedx-splk** [comment]
Hi @GerardPaligot, thanks for opening the issue. Would you happen to have sample code we could see that shows how you're using the `RumFragmentActivityRegisterer`? Typically I think the expectation is that you would use the `AndroidLifecycleInstrumentation.installOn(app)` and that would do the wiring for you. Is that the way you're using it, or are you using the `RumFragmentActivityRegisterer` directly? 

This could be a hint that we need to hide some of the implementation details, if it's not clear enough. Thanks!

**Comment by GerardPaligot** [comment]
Yes, I used this function to add lifecycle instrumentation in my RUM OTeL object:

```kotlin
internal fun OpenTelemetryRumBuilder.addLifecycleInstrumentation(
    screenTracker: VisibleScreenTracker,
    startupTimer: AppStartupTimer = AppStartupTimer()
): OpenTelemetryRumBuilder {
    return this.addInstrumentation { app ->
        AndroidLifecycleInstrumentation.builder()
            .setVisibleScreenTracker(screenTracker)
            .setStartupTimer(startupTimer)
            .setTracerCustomizer { tracer ->
                return@setTracerCustomizer Tracer { spanName ->
                    val component = if (spanName == RumAttributeKeys.APP_START_SPAN_NAME) {
                        AttributeKeys.Features.COMPONENT_APPSTART
                    } else {
                        AttributeKeys.Features.COMPONENT_UI
                    }
                    tracer.spanBuilder(spanName)
                        .setAttribute(AttributeKeys.COMPONENT_KEY, component)
                }
            }
            .setScreenNameExtractor(ScreenNameExtractor.DEFAULT)
            .build()
            .installOn(app)
    }
}
```

But I created a sample app to test this with the minimum of code and it works well. I probably do something wrong somewhere else in my code. I close this and will reopen it if I can reproduce it.
