### ISSUE TITLE
in the other repos we use `publishToSonatype`, i'm not sure what the differences is between that and `publishMavenPublicationToSonatypeRepository`

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-android#58]
in the other repos we use `publishToSonatype`, i'm not sure what the differences is between that and `publishMavenPublicationToSonatypeRepository`

also we don't seem to need `-Pfinal=false` in the other repos

_Originally posted by @trask in https://github.com/open-telemetry/opentelemetry-android/pull/55#discussion_r1312174063_

**Comment by breedx-splk** [comment]
I'm also not entirely sure, but I suspect it might be a difference between `io.github.gradle-nexus.publish-plugin` (https://github.com/gradle-nexus/publish-plugin) and  `maven-publish` (https://docs.gradle.org/current/userguide/publishing_maven.html). 

It looks like core and instrumentation use both....I don't understand why you'd want or need both...

**Comment by LikeTheSalad** [comment]
> I'm also not entirely sure, but I suspect it might be a difference between io.github.gradle-nexus.publish-plugin (https://github.com/gradle-nexus/publish-plugin) and maven-publish (https://docs.gradle.org/current/userguide/publishing_maven.html).
> 
> It looks like core and instrumentation use both....I don't understand why you'd want or need both...

That's right they're different but they complement each other, the `maven-publish` plugin is Gradle's official way to set up and publish maven publications from a project, whereas `io.github.gradle-nexus.publish-plugin` takes the publications created by `maven-publish` and uploads them to maven central, automating the whole process of creating sonatype's staging "repo", then closing and releasing it too. The automation of these processes is the value provided by the nexus publish plugin, as they mention in [maven central's doc](https://central.sonatype.org/publish/publish-gradle/#releasing-the-deployment-to-the-central-repository) where they talk about a plugin named "[Gradle Nexus Staging Plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/)" which was later deprecated in favor of the nexus publish plugin.
