### ISSUE TITLE
[demo-app] Add ability to cause an ANR (application not responding)

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#608]
Much like the ability to crash the application, we want to be able to manually/intentionally trigger an ANR. We should build this capability into the demo application.

Relates to the questions in #496.

**Comment by Victorsesan** [comment]
@breedx-splk Can you please assign this to me? i can give it a try and add the ANR simulation code to the main activity and Implement the ANR Logic to it and you review. Also the repo Readme.md file shows some of the features included in the demo app already includes the ANR feature , does that mean we just have to modify an already implemented ANR feature? if so where can i find the file to work on. Thank You

**Comment by breedx-splk** [comment]
@Victorsesan thank you so much to offering to work on this, but another contributor @magda-woj explained on the weekly SIG meeting today that the code is written and a PR will be submitted right after #627 is merged. 

The help is definitely welcome, so please feel free to look into other issues or just directly submit a PR for something else without being assigned (it's not required). Thanks again.
