### ISSUE TITLE
Send custom token-id in header for all trace & log getting send

### ISSUE THREAD

**Issue by tech-ind-02** [open-telemetry/opentelemetry-android#713]
please help!! How we can send custom token id in header whenever there is traces and logs getting sent to collector. like we are setting endpoint.

![image](https://github.com/user-attachments/assets/d4b21dd8-71d1-4c36-92fa-a09f3338b78f)

**Comment by ddas09** [comment]
@tech-ind-02, you can add a custom header like this in the span/log exporter - 
<img width="883" alt="Screenshot 2024-12-01 at 11 13 03 PM" src="https://github.com/user-attachments/assets/e8127270-c6ac-4414-b374-e9e462ec4cd9">

**Comment by breedx-splk** [comment]
Thanks @ddas09 that's totally the intended API. @tech-ind-02 I'm going to close this for now, please reopen if that answer doesn't work for you or if you would like to continue discussing.
