### ISSUE TITLE
Publish versioned aar artifacts

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#9]
The primary output of the build process is an `.aar` file. This should be versioned (initial version should be 0.1.0) with semver and a github release should be created. The github release should contain the artifact.

The artifact should be published to maven.

**Comment by tonzhan2** [comment]
I'm inclined towards publish to maven

**Comment by breedx-splk** [comment]
I hadn't thought if this until now, but we should probably start by getting snapshot builds publishing first. This would be a workflow that is triggered on merge to `main` branch and publishes with the SNAPSHOT qualifier, which we may not yet support.

@LikeTheSalad what do you think?

**Comment by LikeTheSalad** [comment]
Creating snapshot builds automatically sounds good to me 👍 - after we have the maven central configuration set up we can start doing so right away.

**Comment by LikeTheSalad** [comment]
I think this is done now
